apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: px-mongo-sc
parameters:
  io_profile: db_remote
  repl: "3"
provisioner: pxd.portworx.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
